// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrabowjV-hRHL-zXHz9WXqFv4THDFwHCY',
    appId: '1:433925774395:web:4cb49e165f8e3f06c8101e',
    messagingSenderId: '433925774395',
    projectId: 'email-login-306f1',
    authDomain: 'email-login-306f1.firebaseapp.com',
    storageBucket: 'email-login-306f1.appspot.com',
    measurementId: 'G-7SH2HL8X9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhWOmf0L0YU7Ugzg0yuaVTUUevG2SsX1A',
    appId: '1:433925774395:android:81a40c7ef4168977c8101e',
    messagingSenderId: '433925774395',
    projectId: 'email-login-306f1',
    storageBucket: 'email-login-306f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb2MJiX97PnTdYiys3eqqqfqVjgIczd2M',
    appId: '1:433925774395:ios:e393eed1985326dbc8101e',
    messagingSenderId: '433925774395',
    projectId: 'email-login-306f1',
    storageBucket: 'email-login-306f1.appspot.com',
    iosClientId: '433925774395-79ipl4n66fqu552dou31ulbvl8hkkp6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
